[build]
publish = "public"
command = "./stackbit-build.sh"

  [build.processing]
    skip_processing = false
  [build.processing.images]
    compress = true

  [build.environment]
  HUGO_VERSION = "0.70.0"

